spring:
  config:
    activate:
      on-profile: locale

  datasource:
    url: jdbc:postgresql://localhost:5432/restaurant
    username: postgres
    password: root
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
      naming:
        implicit-strategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyLegacyJpaImpl
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl

    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

    show-sql: false