FROM eclipse-temurin:21-jdk
EXPOSE 8080

ADD target/Restaurant-Reservation-Ordering-System-0.0.1-SNAPSHOT.jar Restaurant-Reservation-Ordering-System-0.0.1-SNAPSHOT.jar
ENTRYPOINT ["java","-jar","/Restaurant-Reservation-Ordering-System-0.0.1-SNAPSHOT.jar"]