pipeline {
    agent any

    stages {
        stage('Build & Test') {
            steps {
                dir('Restaurant-Reservation-Ordering-System') {
                    sh './mvnw clean test'
                }
            }
        }
    }
}