pipeline {
    agent any

    stages {
        stage('Test Jenkins') {
            steps {
                echo 'Jenkins is running from GitHub!'
            }
        }
    }
}

// Jenkins pipeline test