pipeline {
    agent any

    stages {

        stage('Build & Test') {
            steps {
                dir('Restaurant-Reservation-Ordering-System') {
                    sh './mvnw clean test'
                }
            }
        }

        stage('SonarQube Analysis') {
            steps {
                dir('Restaurant-Reservation-Ordering-System') {
                    withSonarQubeEnv('SonarQube') {
                        sh './mvnw verify org.sonarsource.scanner.maven:sonar-maven-plugin:sonar'
                    }
                }
            }
        }
    }
}